channels:
     - hjkgroup
     - defaults
dependencies:
     - openbabel
     - pyyaml
     - scipy
     - pandas
     - scikit-learn
     - beautifulsoup4
     - networkx
     - pip:
       - recommonmark
       - readthedocs-sphinx-ext
     - mock
     - pillow
     - sphinx
     - sphinx_rtd_theme
